remote:
  real:
    driver: orderlyweb::orderlyweb_remote
    args:
      host: covid19-forecasts.dide.ic.ac.uk
      port: 443
      token: $VAULT_AUTH_GITHUB_TOKEN
    primary: true
    master_only: true

fields:
  requester:
    required: false
  author:
    required: false

minimum_orderly_version: 1.1.32
