remote:
  real:
    driver: orderlyweb::orderlyweb_remote
    args:
      host: covid19-forecasts.dide.ic.ac.uk
      port: 443
      token: $VAULT_AUTH_GITHUB_TOKEN
    primary: true
    master_only: true
    
vault:
  addr: https://vault.dide.ic.ac.uk:8200

fields:
  requester:
    required: false
  author:
    required: false

minimum_orderly_version: 1.2.36
global_resources: helper-scripts