# To use external databases, this file must contain the field
# 'database', which contains database configurations, each of which
# must contain a field 'driver' that will be one of RSQLite::SQLite or
# RPostgres::Postgres (other drivers may work too in future, but not
# yet).
#
# For example, a configuration to use Postgres as the source database
# might look like:
#
#   database:
#     source:
#       driver: RPostgres::Postgres
#       args:
#         host: localhost
#         port: 5432
#         user: myuser
#         dbname: databasename
#         password: p4ssw0rd
#
# All arguments in the "args" block will be passed through during the
# 'DBI::dbConnect()' call.
#
# If using SQLite, then the "dbname" argument will be interpreted
# relative to the orderly root if not absolute .  Be sure to exclude
# this path using .gitignore
#
# Other options accepted by RSQLite are allowed but are much less
# commonly useful (as of RSQLite v1.1-2, loadable.extensions,
# cache_size, synchronous, flags, vfs)
database: ~

# It is not necessary to configure a destination driver explicitly
# unless you want to change the default (which is into a SQLite
# database called "orderly.sqlite" at the orderly root.  If you do
# specify it, the options are the same as for "source", e.g.:
#
#   destination:
#     driver: RSQLite::SQLite
#     args:
#       dbname: different.sqlite

# In addition, it may contain a 'fields' section defining custom
# fields, for example:
#
#   fields:
#     comment:
#       required: true
#       type: character
#
# Each field is named, and has two required entries; 'required'
# (either false or true) and 'type' (either 'character' or 'numeric').
#
# The fields must not clash with built-in field names.
fields: ~
