---
title: "ccc"
author: "Pierre Nouvellet"
date: "2019-07"
---

```{r options, include = FALSE, message = FALSE, warning = FALSE, error = FALSE}
library(knitr)

opts_chunk$set(collapse = TRUE)

opts_chunk$set(fig.path='figs/', fig.keep='high', 
               dev=c('png'), fig.width=8, fig.height=8, cache=FALSE,
               tidy=FALSE, warning=FALSE, fig.show="asis"
 	       )

```


NEED to do:
1) input

# Input

```{r}

date_week_finishing <-  as.Date('31/05/2020',format = '%d/%m/%Y')


d1 <- readRDS(
        file = paste0('RData/RtI0_Std_results_week_end_',date_week_finishing,'.SI1.rds' ))

d2 <- readRDS(
        file = paste0('RData/RtI0_Std_results_week_end_',date_week_finishing,'.SI2.rds' ))


```

```{r}


R_last <- list()
Predictions <- list()

for (i in 1:length(d1$Country)){
  R_last[[as.character((d1$Country)[i])]][[1]] <- d1$Rt_last[,i]
  R_last[[as.character((d1$Country)[i])]][[2]] <- d2$Rt_last[,i]
  
  Predictions[[as.character((d1$Country)[i])]][[1]] <- d1$Predictions[[i]]
  Predictions[[as.character((d1$Country)[i])]][[2]] <- d2$Predictions[[i]]
}


d <- list(I_active_transmission = d2$I_active_transmission,
          D_active_transmission = d2$D_active_transmission,
          Country = d2$Country,
          R_last = R_last,
          Predictions = Predictions)

saveRDS(object = d,
        file = paste0('RData/RtI0_Std_results_week_end_',date_week_finishing,'.rds' ))

```